const { NlpManager } = require('node-nlp');
// Create an instance of NlpManager
const manager = new NlpManager({ languages: ['en'] });

const trainingData = [
    { intent: 'greetings.hello', utterances: ['Hi there!', 'Hello!', 'Good morning!', 'Good afternoon!', 'Good evening!'], responses: ['Hello! How can I help you today?', 'Hi! What can I do for you?', 'Good morning! How can I assist you?', 'Good afternoon! How may I help you today?', 'Good evening! What can I do for you?'] },
    { intent: 'information.weather', utterances: ['What\'s the weather like today?', 'How\'s the weather?', 'Is it going to rain today?', 'Do I need an umbrella?', 'What\'s the forecast for tomorrow?'], responses: ['Let me check for you. It\'s sunny with a high of 75°F.', 'The weather is clear and sunny.', 'There is no rain expected today.', 'You won\'t need an umbrella today.', 'Tomorrow\'s forecast is partly cloudy with a chance of rain.'] },
    { intent: 'information.time', utterances: ['What\'s the time?', 'What time is it?', 'Can you tell me the time?', 'What\'s the current time?'], responses: ['The current time is 3:00 PM.', 'It\'s 3:00 PM right now.', 'It is now 3:00 PM.', 'The time is 3:00 PM.'] },
    { intent: 'information.date', utterances: ['What\'s the date today?', 'What\'s today\'s date?', 'Can you tell me the date?', 'What\'s the current date?'], responses: ['Today is July 4, 2024.', 'It\'s July 4, 2024.', 'The date today is July 4, 2024.', 'Today\'s date is July 4, 2024.'] },
    { intent: 'information.news', utterances: ['What\'s the news today?', 'Tell me the latest news.', 'What\'s happening in the world?', 'Any news updates?'], responses: ['Here are the latest headlines: one Ant die after drink coca-cola.', 'Today\'s top news: dogs goes viral after his first song release.', 'The latest news updates: the temperature reach to 50 degree in last 7 days.', 'Here are some recent news updates: today Gandhiji said we all are independent .'] },
    { intent: 'assistance.account', utterances: ['I need help with my account.', 'How do I reset my password?', 'Can you help me with my account issues?', 'I need assistance with my account.'], responses: ['Sure, I can help with that. What seems to be the problem?', 'To reset your password, go to the settings page and click on "Forgot Password".', 'Please describe the issue you\'re facing with your account.', 'I\'m here to help with your account issues. What do you need assistance with?'] },
    { intent: 'assistance.technical', utterances: ['I need technical support.', 'Can you help me with a technical issue?', 'I\'m having trouble with my device.', 'I need help with a technical problem.'], responses: ['I\'m here to help. Please describe the issue you\'re facing.', 'What technical problem are you experiencing?', 'Tell me more about the trouble you\'re having with your device.', 'I can assist you with your technical issue. What seems to be the problem?'] },
    { intent: 'product.inquiry', utterances: ['Tell me about your products.', 'Do you have any discounts?', 'What are your best-selling items?', 'What products do you offer?', 'Show me your products.'], responses: ['We offer a variety of products including electronics, clothing, and home goods.', 'Yes, we have ongoing discounts on selected items. Check our website for more details.', 'Our best-selling items include the latest smartphones, laptops, and smartwatches.', 'We have a wide range of products including electronics, clothing, and more.', 'You can view all our products on our website.'] },
    { intent: 'order.transaction', utterances: ['How do I track my order?', 'I want to cancel my order.', 'How can I return a product?', 'Can I get a refund?', 'Where is my order?'], responses: ['You can track your order by entering your tracking number on our tracking page.', 'Please provide your order number, and I’ll assist you with the cancellation.', 'To return a product, visit our returns page and follow the instructions.', 'Refunds can be requested through our customer service. Please provide your order details.', 'Your order status can be checked using your tracking number on our website.'] },
    { intent: 'farewell.goodbye', utterances: ['Thanks for your help!', 'Goodbye!', 'See you later!', 'Thank you!', 'Bye!'], responses: ['You\'re welcome! If you have any more questions, feel free to ask.', 'Goodbye! Have a great day!', 'See you! Take care!', 'You\'re welcome! Have a great day!', 'Bye! Take care!'] },
    { intent: 'smalltalk.howareyou', utterances: ['How are you?', 'What\'s your name?', 'Do you like music?', 'How is your day?', 'What do you do?'], responses: ['I\'m doing well, thank you. How about you?', 'I’m your friendly chatbot assistant. How can I help you?', 'I love music! What’s your favorite song?', 'My day is going great! How about yours?', 'I\'m here to assist you with any questions or issues you have.'] },
    { intent: 'custom.fact', utterances: ['Tell me a fun fact.', 'What is AI?', 'Can you recommend a book?', 'Tell me something interesting.', 'Do you know any trivia?'], responses: ['Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.', 'AI stands for Artificial Intelligence. It\'s a field of computer science that aims to create intelligent machines that can mimic human behavior and thinking.', 'Sure! I recommend "To Kill a Mockingbird" by Harper Lee. It\'s a classic!', 'Here\'s something interesting: The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.', 'Here\'s a trivia for you: The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in the heat.'] },
    { intent: 'personalization.reminder', utterances: ['What\'s my name?', 'Remind me to call John tomorrow.', 'What\'s my schedule for today?', 'Can you set a reminder for me?', 'Do I have any appointments?'], responses: ['Your name is stored in my memory, but I need you to tell me your name first.', 'I\'ve set a reminder to call Nikhil tomorrow.', 'Here is your schedule for today: go to walk and do excercise.', 'I can set a reminder for you. What would you like to be reminded of?', 'Let me check your appointments: it is on wednesday.'] },
    { intent: 'info.help', utterances: ['How do I contact support?', 'Where can I find more information?', 'What should I do if I have an issue?', 'I need help.', 'Can you assist me?'], responses: ['You can contact support by emailing hawkscode@gmail.com.', 'For more information, visit our website.', 'If you have an issue, please describe it to me, and I will do my best to help.', 'I\'m here to help. What do you need assistance with?', 'Sure, I\'m here to assist you. What seems to be the problem?'] },
    { intent: 'info.feedback', utterances: ['I want to give feedback.', 'How can I leave a review?', 'Where can I provide feedback?', 'Can I give you feedback?', 'I have some feedback.'], responses: ['We appreciate your feedback! Please leave a review on our website.', 'You can leave a review by visiting our feedback page.', 'Feel free to provide your feedback here or on our website.', 'Of course! Please share your feedback with us.', 'Thank you for your feedback! We value your opinion.'] },
    { intent: 'directions.location', utterances: ['How do I get to the nearest gas station?', 'Where is the closest restaurant?', 'Can you give me directions to the mall?', 'I need directions to the airport.', 'Where is the nearest hospital?'], responses: ['The nearest gas station is 2 miles away on Main Street.', 'The closest restaurant is 5 minutes away on foot.', 'To get to the mall, head north on 5th Avenue for 3 miles.', 'The airport is 10 miles away. Follow the highway signs for the quickest route.', 'The nearest hospital is 3 miles away on Elm Street.'] },
    { intent: 'local.info', utterances: ['What events are happening today?', 'Can you recommend a local attraction?', 'What\'s the best place to visit in this city?', 'Are there any events today?', 'What\'s a good place to eat around here?'], responses: ['Here are some events happening today: might have rain today.', 'I recommend visiting the city park. It\'s beautiful this time of year.', 'The best place to visit in this city is the downtown museum.', 'Yes, there are several events today: [list events].', 'A great place to eat around here is Joe\'s Diner.'] },
    { intent: 'transport.info', utterances: ['What\'s the best way to get around the city?', 'How do I get to the train station?', 'Is there a bus stop nearby?', 'Can you call me a taxi?', 'What\'s the closest subway station?'], responses: ['The best way to get around the city is by subway.', 'To get to the train station, take the subway to Central Station.', 'Yes, there\'s a bus stop two blocks away.', 'Sure, I can call a taxi for you.', 'The closest subway station is 5 minutes away on foot.'] },
    { intent: 'emergency.info', utterances: ['I need emergency help.', 'Call 911.', 'Where is the nearest police station?', 'I have an emergency.', 'Can you help in an emergency?'], responses: ['For emergencies, please call 911 immediately.', 'Dial 911 for emergency assistance.', 'The nearest police station is 1 mile away on Main Street.', 'If you have an emergency, call 911.', 'In case of an emergency, it is best to call 911 directly.'] },
    { intent: 'fallback', utterances: ['Sorry, I didn\'t understand that.', 'I\'m not sure what you mean.', 'Could you please rephrase that?', 'I didn\'t catch that.', 'Please provide more details.'],responses: ['I\'m sorry, I couldn\'t understand your request. Could you please try again?', 'Apologies, I\'m not sure how to respond to that. Could you rephrase your question?', 'I didn\'t quite get that. Can you provide more context or details?', 'Sorry, I didn\'t understand what you said. Could you clarify?', 'I\'m not able to process that request. Could you try asking in a different way?'] }
  ];
  

// Add the training data to the manager
trainingData.forEach(data => {
  data.utterances.forEach(utterance => {
    manager.addDocument('en', utterance, data.intent);
  });
  data.responses.forEach(response => {
    manager.addAnswer('en', data.intent, response);
  });
});

// Train the model
(async () => {
  await manager.train();
  manager.save('model2.nlp');
  console.log('Model trained and saved');
})();
